### PR TITLE
Estonian local flavor: added business registry code field

### PR DESCRIPTION
**Pull request by kendas**
I've added the field to validate the Estonian business registry code (äriregistri registrikood).

Although I couldn't find a standard or a legitimate source for the business registry code structure, it seems to have the same checksum method as the personal identification code. Even though its 8 characters long, the basic math would make sense (just imagine the last 3 non-checksum numbers being 0's). After testing a fair bit of known correct codes, the checksum works.

The `EEBusinessRegistryCode` field itself behaves in a very similar manner to the existing `EEPersonalIdentificationCode` field.

### CODE REVIEW

**Comment by intgr** [comment]
+1 for merge.

**Comment by intgr** [comment]
@jezdez Can this be merged, please? It's been over 6 months now.

**Comment by nagisa** [comment]
The only blocker I see is lack of `.. version_added:: 1.2` in the docstring. As for correctness I’m inclined to trust @intgr.

**Comment by intgr** [comment]
Please merge this.

**Comment by nagisa** [comment]
Sorry for taking so long to merge this. I’ve totally forgotten all about this and github doesn’t send notifications when new commits are added to PRs.

Thanks for submitting this, I will merge.

**Comment by kendas** [comment]
Thank you for pointing out the no notification thing @nagisa. In the future I will make a comment on such occasions.

**Pull request merged**
