### PR TITLE
Removed Python 2 compatibility

### PR DESCRIPTION
**Pull request by claudep**
This removes Python 2 compatibility and makes django-localflavor run with next Django version (3.0).

### CODE REVIEW

**Comment by benkonrath** [comment]
Thanks for this! I was roughly planning a 2.2 release at the end of the month. I think it's better to merge this after the 2.2 release so that we can support Django 1.11 & 2.2 in our 2.2 release. What do you think?

**Comment by claudep** [comment]
Sure, that's a good plan!

**Comment by claudep** [comment]
Just rebased the branch.

**Comment by claudep** [comment]
See https://code.djangoproject.com/ticket/30399 about the failures we get on the master branch.

**Comment by claudep** [comment]
The PR was committed, I triggered a new build and the tests now pass on master!

**Pull request merged**
