### PR TITLE
Change regex of BRZipCodeField

### PR DESCRIPTION
**Pull request by gilsondev**
I'm change the regex to support many types of numbers:

 - 71000-000
 - 71.000-000
 - 71000000

### CODE REVIEW

**Comment by claudep** [comment]
Please remove the .po/.mo changes from the patches. Those are handled separately through Transifex.

**Comment by gilsondev** [comment]
Ok

**Comment by gilsondev** [comment]
Removed

**Comment by gilsondev** [comment]
Now, need access the django-localflavor in Transifex. I'm send a request to come in.

**Comment by gilsondev** [comment]
@claudep files removed

**Comment by claudep** [comment]
I'll let @avelino do the merge.

**Comment by avelino** [comment]
Why validate point in CEP (zipcode of Brazil)?

**Comment by gilsondev** [comment]
Yes, the point in zipcode is not default to use. I go remove this.

**Comment by avelino** [comment]
@gilsondev I think this solution is bad, if a user puts a "," for example would break their implementation.

**Comment by gilsondev** [comment]
So, you think better not change the pattern?

**Comment by avelino** [comment]
Thinking about the use of lib, with this implementation not worth, if it is a generic implementation Yes.
Where did you get this need?

**Comment by gilsondev** [comment]
I thought it would be interesting to have more than one format for zipcode

**Pull request closed without merging**
