### PR TITLE
Deprecations and cleanups

### PR DESCRIPTION
**Pull request by benkonrath**
* More work on depreciations (see #258).
* Drop support for Django 1.9
* Small cleanup for IBAN tests.

### CODE REVIEW

**Comment by claudep** [comment]
Fine, but do we gain anything by removing 1.9 support? If not, I wonder if it's worth it.

**Comment by benkonrath** [comment]
There's no specific gain for dropping support for 1.9 except being explicit about not supporting version of Django that are no longer supported. I'll remove this change for now.

**Comment by claudep** [comment]
I see your point. But as we generally gain nothing technically when dropping "intermediate" unsupported releases, my opinion is that we should keep that support. But this is in no way a final decision and this might be the subject of further discussions (e.g. on django-developers).

**Comment by benkonrath** [comment]
Yeah, I understand it's just your opinion and I also see your point. For me it's not really a big deal either way - I dropped 1.9 support to save me a bit of time waiting for CI test and because I don't want to fix any bugs in old versions of Django. But can just decide to drop support if or when 1.9 (or any other unsupported version) is holding us back like we have in the past.

**Pull request merged**
