### PR TITLE
Fix rare inconsistencies with FRNationalIdentificationNumber 

### PR DESCRIPTION
**Pull request by leo-naeka**
This PR fixes some french identification numbers errors occurring with these cases:
- People with imaginary birth month (when not known or unverifiable)
- People born in Corsica after 2000

--

Based on these (reliable) sources:
- https://www.e-ventail.fr/ss/Satellite/e-ventail/documentation/fiches-techniques/numero-securite-sociale.html

```
La signification des chiffres est la suivante : 
    1 sexe : 1 pour les hommes, 2 pour les femmes;
    2 et 3 deux derniers chiffres de l'année de naissance (*);
    3 et 4 mois de naissance (01 à 12) (**);
    6 et 7 département de naissance (2A ou 2B pour les personnes nées en Corse à partir de 1976, 98 pour les DOM, 99 pour les personnes nées à l'étranger ; 91, 92 ou 93 pour certaines personnes nées en Algérie sous administration française);
    8, 9 et 10 numéro d'ordre de la commune de naissance dans le département;
    11, 12 et 13 numéro d'ordre de l'acte de naissance.

(*) L’année du NIR doit être égale à l’année renseignée dans la date de naissance. 
L’année du NIR doit être inférieure à l’année en cours et supérieure à l’année en cours moins 120. 
Exemple : Pour une déclaration déposée en 2006 concernant les salaires de 2005. L’année de naissance pourra prendre une valeur de 1885 à 2005.

(**) Le mois de naissance peut aussi être compris entre 30 et 42, entre 50 et 99 ou égal à 20 ou 99 ; pour les personnes dont on ne connaît pas le mois de naissance du fait d’absence de registre d’état civil dans certains pays étrangers.
```

- http://www.dsn-info.fr/documentation/dsn_cahier_technique_phase1.pdf (p. 72-73)

### CODE REVIEW

**Comment by benkonrath** [comment]
@claudep Do you have time to review this?

**Comment by claudep** [comment]
This looks good. It would be nice if the third commit could be split and merged in the two previous commits.

**Comment by leo-naeka** [comment]
@claudep, I rebased and meld the third commit into the second one.

**Comment by claudep** [comment]
Thanks!

**Pull request merged**
