### PR TITLE
Fix for slovenian tax number validation when control code is 11

### LINKED ISSUE #206: local-flavor SI: SITaxNumberField should not raise exception when control code is 11
local-flavor 1.2 for Slovenia (SI) has a bug in file localflavor/si/forms.py on line 111:
`if chk == 10:`
which should be replaced with
`if chk == 10 or chk == 11:`

[Tax number check in Slovenia](http://www.davkoplacevalci.com/davcni-klepet/prikaz/razsirjen/24227/kontrola-davcne-stevilke---kako--)

### PR DESCRIPTION
**Pull request by ladolf**

### CODE REVIEW

**Comment by benkonrath** [comment]
Thanks for making a pull request. It looks like you didn't update the tests (or didn't commit / push you changes) so the tests are failing because of your change.

**Comment by ladolf** [comment]
I am confused. I committed an pushed to the repository then I clicked "compare & pull request" and "create pull request" as in tutorial (https://www.thinkful.com/learn/github-pull-request-tutorial). Why are then 1 commit and 3 file changes visible?

**Comment by nagisa** [comment]
It is correct. You've changed 3 distinct files (authors, change log, and
the python file) within a single commit. Each commit may change multiple
files. Similarly each PR may contain multiple commits made over time.

**Comment by nagisa** [comment]
The problem is lack of updated tests.

When you add, commit and push the updated tests, the PR should get updated
with the commit containing tests automatically.

**Comment by benkonrath** [comment]
I'm closing this issue because a control code of 11 seems to indicate an invalid SI tax number. For details see my comment in #206.

**Pull request closed without merging**
