### PR TITLE
Added German translation for BIC (Bank Identifier Code) error messages.

### PR DESCRIPTION
**Pull request by valnico**
Added German translation for the three error messages of the `BICValidator`.

### CODE REVIEW

**Comment by benkonrath** [comment]
Translations are managed through Transifex:

https://www.transifex.com/django/django-localflavor/

You'll have to signed up to the German translation team to add this. Thanks.

**Comment by valnico** [comment]
Thanks. I just signed up in Transifex and applied to join the team.

**Comment by valnico** [comment]
Hi @benkonrath, I applied for Italian and German translations on Transifex, but only Italian has been approved. Do you have any permission to approve me for German on Transifex? 
I ask here because I can't find any way to contact the project admins on Transifex.

**Comment by benkonrath** [comment]
I don't have permissions on Transifex but maybe Markus can help out.

@MarkusH Can you help @valnico with this request?

**Comment by MarkusH** [comment]
I accepted your Transifex application, @valnico . Buzz me when you added the strings?

**Pull request closed without merging**
