### PR TITLE
Added cities of Israel and postal code regions in Great Britain

### PR DESCRIPTION
**Pull request by theBrownBug**
Added cities in Israel. 
Added postal code regions of Great Britain

Source : https://www.britannica.com/topic/list-of-cities-and-towns-in-Israel-2060226
https://en.wikipedia.org/wiki/List_of_postcode_areas_in_the_United_Kingdom

### CODE REVIEW

**Comment by theBrownBug** [comment]
Added postal code regions of Great Britain

**Comment by claudep** [comment]
Thanks, but please do not mix two unrelated changes in the same pull request. Please split them into two PRs.

**Comment by theBrownBug** [comment]
Noted.

**Comment by benkonrath** [comment]
I'm closing this PR - please create separate PRs for each logical change you'd like to contribute. Thanks.

**Pull request closed without merging**
