### PR TITLE
Adding the Tunisian Local Flavor to Django.

### PR DESCRIPTION
**Pull request by pyghassen**
I think Tunisia is missing as a local flavor to Django.

### CODE REVIEW

**Comment by pyghassen** [comment]
I'm not sure what this error means:
 ERROR: InvocationError: '/home/travis/build/pyghassen/django-localflavor/.tox/py26-1.5/bin/invoke test'

But I don't think it's related to the pull request.

**Comment by avelino** [comment]
Error on run build:

    localflavor/generic/checksums.py:7:1: E402 module level import not at top of file
    localflavor/es/forms.py:109:9: E731 do not assign a lambda expression, use a def
    localflavor/es/forms.py:182:9: E731 do not assign a lambda expression, use a def
    localflavor/pt/forms.py:58:9: E731 do not assign a lambda expression, use a def
    localflavor/pt/forms.py:59:9: E731 do not assign a lambda expression, use a def

**Comment by pyghassen** [comment]
ok I will check them, but I think they existed before my pull request.

**Comment by pyghassen** [comment]
Finally All green on Travis, many modules were outdated in fact @avelino

**Comment by pyghassen** [comment]
Hi @jezdez I think it's about time for 1.2 release.

**Comment by pyghassen** [comment]
Some day this pull request will be merged!

**Comment by claudep** [comment]
Hi Ghassen,
I think your PR still needs some cleaning. The 3 first commits should be merged + the 1a7714e commit. It seems that all other commits are not related to the Tunisian flavor, and hence should be put aside. They could be proposed as a separate pull request. Then rebase your commit on current master. Thanks for your work until now.

**Comment by pyghassen** [comment]
Hello @claudep
The tests were failing because of those bugs, so I fixed them first then I added my code to the merge, otherwise the Travis test result will be red and github will reject my pull request automatically.

I think the best way to do it to start over hoping this time it will be merged.

**Comment by claudep** [comment]
Sure, I'll try to follow more closely this time.

**Comment by pyghassen** [comment]
I have to checks failing on python 3.2 but it's not related to django-localflavor really.
It was pip exception that blew it.

**Comment by claudep** [comment]
Sure, failures are unrelated to your patch. Could you now please squash your commits?

**Comment by pyghassen** [comment]
Hi @claudep,
I checked the logs it was related to pip, and when I checked pip I found out that they drop support for python3.2 on the latest vision, so there to solution whether drop support for python3.2 on django-localfalvor, or just freeze pip version to 7.1.2 so the test can pass.
But I don't know how the pip version is setup on travis, I checked the requirement files and I did not find it.
Can you give me some pointers please to make all the tests pass.

**Comment by claudep** [comment]
No problem, just ignore the failures, they will not block your patch to be committed. We just need a single commit, hence the squash request. If it's easier for you to create a new clean pull request, just do it.

**Comment by pyghassen** [comment]
I spend too many hours digging for the problem, finally I fixed it, It's all green now.

**Comment by claudep** [comment]
Thanks Ghassen. pip issue has been pushed in d1ba10a8e6, and the local flavor in b74351eb89.

**Pull request closed without merging**
