### PR TITLE
Added a model field for Ecuadorian provinces

### PR DESCRIPTION
**Pull request by jleeothon**

### CODE REVIEW

**Comment by benkonrath** [comment]
@jleeothon Thanks for your contribution and sorry for the delay in finishing off this review. Can you rebase this PR and squash the two commits into one? Once that's done, I'll merge this. Thanks.

**Comment by jleeothon** [comment]
Ack. Let me get home and I'll take care of this.

**Comment by benkonrath** [comment]
@jleeothon I rebased this PR and merged it through #179. I added jleeothon to the authors list but I can change it to your real if you want - you just have to give it to me. :) Thanks again for your contribution.

**Comment by jleeothon** [comment]
@benkonrath :cry: I'm so sorry for forgetting to merge this!; I was traveling around a bit. If you have time, my name is Johnny Lee Othon. :smile: Thank you!

**Comment by benkonrath** [comment]
@jleeothon No problem. I actually found your name on your github profile and I've already updated the authors list:
https://github.com/django/django-localflavor/commit/6c048702bd663ddce5aedbd1a08d9dd25f9dcb34

**Pull request closed without merging**
