### PR TITLE
Add a pull request review checklist to CONTRIBUTING.

### PR DESCRIPTION
**Pull request by benkonrath**
This is a checklist that I've developed for reviewing PRs. I'd like to publish so we can have a reference for contributors to look at before they submit a PR.

Let me know if there's a better place for this or if you have any suggestions. Thanks.

### CODE REVIEW

**Comment by nagisa** [comment]
Similarly to my suggestion to use bots for finding out maintainers, I think many of these checkpoints can (and should) be automatically checked for by some sort of automated means (travis?).

**Comment by benkonrath** [comment]
I agree that automating this kind of thing is good. It's sometimes hard to justify spending time on the automation for a small project like localflavor but it's something to work towards.

In the meantime, I'm going to add this to a pull request template instead of adding this to CONTRIBUTING.
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by benkonrath** [comment]
Fixed via https://github.com/django/django-localflavor/commit/cad42c2eed9e69908f12124f4e246b79b8b10f57.

**Comment by benkonrath** [comment]
@nagisa Do you know of tool we can use to check for the `..version_added` markers?

**Comment by nagisa** [comment]
@benkonrath the most trivial way to do it would be to have a script which checks for existence of it on newly added API and run the script during CI.

**Pull request closed without merging**
