### PR TITLE
added areas in Kuwait

### PR DESCRIPTION
**Pull request by Dreamersoul**
**Please replace these instructions with a description of your change. The
'New Fields Only' section should be removed if your pull request
doesn't add any new fields.**

Thanks for your contribution!

A checklist is included below which helps us keep the code contributions
consistent and helps speed up the review process. You can add additional
commits to your pull request if you haven't met all of these points on your
first version.

**All Changes**

- [x] Add an entry to the docs/changelog.rst describing the change.

- [x] Add an entry for your name in the docs/authors.rst file if it's not
      already there.

- [x] Adjust your imports to a standard form by running this command:

      `isort --recursive --line-width 120 localflavor tests`

**New Fields Only**

- [x] Prefix the country code to all fields.

- [x] Field names should be easily understood by developers from the target
      localflavor country. This means that English translations are usually
      not the best name unless it's for something standard like postal code,
      tax / VAT ID etc.

- [x] Add meaningful tests. 100% test coverage is not required but all
      validation edge cases should be covered.

- [ ] Add `.. versionadded:: <next-version>` comment markers to new
      localflavors.

- [x] Add documentation for all fields.

### CODE REVIEW

**Comment by Dreamersoul** [comment]
i dont know why but the `isort --recursive --line-width 120 localflavor tests` changed all the test files for some reason

sorry if i missed something this is the first time i contribute here please let me know if something is missing

**Comment by Dreamersoul** [comment]
are there any core contributors that can help me with this PR? i dont know why it is failing

**Comment by claudep** [comment]
Hey Hamad,
Not related to the failure, but you should first revert all the blank line removal in your second commit. These unneeded changes make your pull request more difficult to review.
Then, follow the advice in the failure: set `self.maxDiff = None` in your test case, and you might then see where is the output difference.

**Comment by Dreamersoul** [comment]
Thank you @claudep I have reverted what `isort` did to the files not related to my commit and the tests pass now!
However I don't know what to do to satisfy the following requirement:
```
Add .. versionadded:: <next-version> comment markers to new
localflavors.
```

**Comment by claudep** [comment]
You can grep the code for `versionadded` to see what it looks like.
See some docstrings of https://github.com/django/django-localflavor/blob/master/localflavor/au/validators.py for example.

**Comment by Dreamersoul** [comment]
@claudep alright done :+1:  thanks for your help :smile:

**Comment by benkonrath** [comment]
Merged via e51e52f4968cdb18d3b1f30189f929becfe3f340.

Thanks!

**Pull request closed without merging**
