### PR TITLE
Renamed the new French regions (2016 reform).

### PR DESCRIPTION
**Pull request by batisteo**
The names of the new regions were adopted. Four names changed:
Hauts-de-France, Nouvelle-Aquitaine, Grand-Est and Occitanie.

Wikipedia source: [fr.wikipedia.org/wiki/Région_française#Choix_du_nom_des_nouvelles_régions_en_2016](https://fr.wikipedia.org/wiki/Région_française#Choix_du_nom_des_nouvelles_r.C3.A9gions_en_2016)

**All Changes**

- [x] Add an entry to the docs/changelog.rst describing the change.

- [x] Add an entry for your name in the docs/authors.rst file if it's not
      already there.

- [ ] Adjust your imports to a standard form by running this command:

      `isort --recursive --line-width 120 localflavor tests`

**New Fields Only**

- [ ] Prefix the country code to all fields.

- [ ] Field names should be easily understood by developers from the target
      localflavor country. This means that English translations are usually
      not the best name unless it's for something standard like postal code,
      tax / VAT ID etc.

- [ ] Prefer '<country code>PostalCodeField' for postal codes as it's
      international English; ZipCode is a term specific to the United
      States postal system.

- [ ] Add meaningful tests. 100% test coverage is not required but all
      validation edge cases should be covered.

- [ ] Add `.. versionadded:: <next-version>` comment markers to new
      localflavors.

- [x] Add documentation for all fields.

### CODE REVIEW

**Comment by batisteo** [comment]
BTW, I kind of dislike using _new_. I would prefer using `REGION_2016_CHOICES` for example.
In few years it won't be new. And it might be new new regions in a while.

**Comment by benkonrath** [comment]
@aaugustin @alix- Can you look over these proposed changes and give your opinion of using "2016" instead of the "new" in the names? Thanks.

**Comment by alix-** [comment]
@batisteo Do you have any offical source for these changes ? Are they in effect today ?

According to Insee, the official regions are still the ones I implemented in #260 (https://www.insee.fr/fr/information/2114819#titre-bloc-30)

**Comment by batisteo** [comment]
@alix- I've got this at the moment:
`curl 'https://www.insee.fr/fr/metadonnees/geographie-administrative/cog/suggestion' -d '{"q":"7","filters":[{"field":"geographie_codeNiveau","values":["REG"]}],"sortFields":[]}' -H 'Content-Type: application/json'`

**Comment by batisteo** [comment]
And this: https://www.insee.fr/en/recherche/recherche-geographique?geo=REG-32+REG-44+REG-75+REG-76

**Comment by alix-** [comment]
Looks good to me, the changes seem legit (always takes a while for these kind of changes to propagate across official websites).
I'm also in favour of changing _new_ to _2016_.

**Comment by batisteo** [comment]
Maybe this as well: http://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Les-noms-des-nouvelles-regions-sont-actes

**Comment by alix-** [comment]
If you want these changes accepted, you should fix the failing tests (they check for a specific HTML output containing the regions names).

**Comment by benkonrath** [comment]
I'm hoping to do the 1.4 release in a couple of weeks and it would be nice to get the name changes and the new -> 2016 change in before the release. Thanks.

**Comment by benkonrath** [comment]
Thanks!

**Comment by batisteo** [comment]
Thanks @benkonrath and @alix- for your quick feedback!

**Comment by aaugustin** [comment]
A bit late to the party — this looks good. Thanks @batisteo.

**Pull request merged**
