### PR TITLE
Fix problem in ES validating NIE numbers starting with Y and Z.

### PR DESCRIPTION
**Pull request by danielmaxx**
Some time ago this [ticket](https://github.com/django/django-localflavor/issues/127) was opened but not correctly fixed.

The checksum should be calculated by prepending the index of the first letter. More reference can be found here: https://es.wikipedia.org/wiki/N%C3%BAmero_de_identificaci%C3%B3n_fiscal#D.C3.ADgito_de_control_para_n.C3.BAmeros_de_DNI_o_NIE

### CODE REVIEW

**Comment by benkonrath** [comment]
This looks great, thanks! Can you just add a couple of housekeeping items:
* Add your name to `docs/authors.rst` if it's not already there.
* Add an entry to the `docs/changelog.rst`

Thanks.

**Comment by danielmaxx** [comment]
Done! I hope everything is fine now.

Many thanks for the kind help!

**Comment by benkonrath** [comment]
Looks good. Can you just rebase from master and squash the commits? Thanks!

**Comment by benkonrath** [comment]
I took care of the rebase and squash. I also fixed a small issue with changelog. Thanks for your help. Please do send in more fixes if you find anymore problems.

Fixed via e37786d6bce2a30531bf23fd83d4862cc8e26f27.

**Pull request closed without merging**
