### PR TITLE
Added the Moroccan localflavor

### PR DESCRIPTION
**Pull request by daker**
**Changes**

* Added regions and provinces data.
* Added forms helpers for select widgets.
* ~~Added PhoneNumber field.~~
* Added PostalCode field.

**All Changes**

- [x] Add an entry to the docs/changelog.rst describing the change.

- [x] Add an entry for your name in the docs/authors.rst file if it's not
      already there.

- [x] Adjust your imports to a standard form by running this command:

      `isort --recursive --line-width 120 localflavor tests`

**New Fields Only**

- [x] Prefix the country code to all fields.

- [x] Field names should be easily understood by developers from the target
      localflavor country. This means that English translations are usually
      not the best name unless it's for something standard like postal code,
      tax / VAT ID etc.

- [x] Prefer '<country code>PostalCodeField' for postal codes as it's
      international English; ZipCode is a term specific to the United
      States postal system.

- [x] Add meaningful tests. 100% test coverage is not required but all
      validation edge cases should be covered.

- [x] Add `.. versionadded:: <next-version>` comment markers to new
      localflavors.

- [x] Add documentation for all fields.

### CODE REVIEW

**Comment by moughamir** [comment]
Nice job!!

**Comment by benkonrath** [comment]
Thanks for you contribution. We're in the process of deprecating the phone number fields in localflavor. We now recommend that people use https://github.com/stefanfoulis/django-phonenumber-field. Could you remove the phone number field after which I'll do a full review. Thanks!

**Comment by claudep** [comment]
Generally, geographic names are marked for translation. I can suppose for example that one may want to translate the names to Arabic. It's not a requirement, just a suggestion.

**Comment by benkonrath** [comment]
Thanks @claudep . This is my mistake, I'll correct it.

**Pull request merged**
