### PR TITLE
Update locale uk and ru languages

### PR DESCRIPTION
**Pull request by darkarchon**
added original names of Ukrainian regions to Ukrainian and Russian locale's
[Ukrainian wiki](https://uk.wikipedia.org/wiki/%D0%90%D0%B4%D0%BC%D1%96%D0%BD%D1%96%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%B8%D0%B9_%D1%83%D1%81%D1%82%D1%80%D1%96%D0%B9_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B8#%D0%A2%D0%B5%D1%80%D0%B8%D1%82%D0%BE%D1%80%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D1%96_%D0%BE%D0%B4%D0%B8%D0%BD%D0%B8%D1%86%D1%96_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B8_%D0%B2%D0%B8%D1%89%D0%BE%D0%B3%D0%BE_%D1%80%D1%96%D0%B2%D0%BD%D1%8F_%D1%82%D0%B0_%D1%97%D1%85%D0%BD%D1%96%D0%B9_%D1%81%D0%BA%D0%BB%D0%B0%D0%B4)
[Russian wiki](https://ru.wikipedia.org/wiki/%D0%90%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%B5_%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%8B#%D0%90%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%BE-%D1%82%D0%B5%D1%80%D1%80%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%B5%D0%B4%D0%B8%D0%BD%D0%B8%D1%86%D1%8B_%D0%BF%D0%B5%D1%80%D0%B2%D0%BE%D0%B3%D0%BE_%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D1%8F)

**All Changes**

- [x] Add an entry to the docs/changelog.rst describing the change.

- [ ] Add an entry for your name in the docs/authors.rst file if it's not
      already there.

### CODE REVIEW

**Comment by benkonrath** [comment]
Thanks for the PR. We use Transifex for translations so unfortunately we can't merge this work. You'll need to signup to Transifex and join the relevant language team and add the translations there.

https://www.transifex.com/django/django-localflavor/

Thanks again for the work here. I'm looking forward to seeing these translations included through Transifex.

**Comment by darkarchon** [comment]
Still waiting for acceptance 
https://www.transifex.com/django/django-localflavor/

**Comment by benkonrath** [comment]
@claudep Is there anything you can do to help @darkarchon get access to Transifex?

**Comment by claudep** [comment]
Maybe @MechanisM could help?

**Comment by darkarchon** [comment]
two weeks... nothing

**Comment by claudep** [comment]
What's your transifex username?

**Comment by darkarchon** [comment]
Alexdutch

**Pull request closed without merging**
